import std/[unittest]
import cattag

const tagFromHtmlAttributeType: string = " rel='stylesheet'"
test "Sugar assignment from HtmlAttribute":
    check tagFromHtmlAttributeType == $(rel <=> "stylesheet")

const simpleElement: string = """<p>Hello world!</p>"""
const simpleElementWithClass: string = """<p class='center'>Hello world!</p>"""
test "Default autogenerated procs":
    check simpleElement == $p(html"Hello world!")
    check simpleElementWithClass == $p(html"Hello world!").addattr("class", "center")

const customAttrElementInput: string = """<input id='some-checkbox' type='checkbox' />"""
const customAttrElementImg: string = """<img alt='very cool image' src='image.png' />"""
test "Custom attribute autogenerated procs":
    check customAttrElementInput == $input("checkbox", "some-checkbox")
    check customAttrElementImg == $img("image.png", "very cool image")

const customAttrElementWithChildren: string = """<optgroup label='Cool Cats'>
    <option selected value='cat_lucy'>Lucy</option>
    <option value='cat_findus'>Findus</option>
    <option value='cat_nyan_cat'>Nyan-Cat</option>
</optgroup>"""
test "Custom attribute autogenerated procs with children":
    check customAttrElementWithChildren == $optgroup("Cool Cats",
        option("cat_lucy", true, "Lucy"),
        option("cat_findus", "Findus"),
        option("cat_nyan_cat", "Nyan-Cat")
    )
