import std/[strutils, strformat]
import parser

var output: OutputFile = newOutputFile("cssProperties.nim")
output.lines = @[
    "## CSS Properties",
    "## ===============",
    "##",
    "## This module is autogenerated with a list of CSS Properties.",
    "",
    "type CssProperty* = string",
    "",
    "const"
]
