import std/[strutils, strformat]
import parser

const needsQuotes: seq[string] = @[]

var output: OutputFile = newOutputFile("cssProperties.nim")
output.lines = @[
    "## CSS Properties",
    "## ==============",
    "##",
    "## This module is autogenerated with a list of CSS properties.",
    "",
    "type CssProperty* = string",
    "",
    "const"
]

proc toCodeRepr(raw: string): string =
    var nextIsCapital: bool = false
    for i, c in raw:
        let thisIsCapital: bool = nextIsCapital
        nextIsCapital = false
        # Special case for special first char stuff:
        if i == 0:
            var quitNow: bool = true
            case c:
                of '-':
                    nextIsCapital = false # Beginning with '-' -> should not be capitalised
                of '@':
                    result.add(
                        if thisIsCapital: "At"
                        else: "at"
                    )
                    nextIsCapital = true
                else:
                    quitNow = false
            if quitNow: continue

        # Normal behaviour:
        if c == '-':
            # Dash:
            nextIsCapital = true
            continue
        # Alphanumeric:
        let current: string = if thisIsCapital: toUpper($c) else: $c
        result.add current

for line in parseFileLines("css-properties-mdn.txt"):
    let parts: seq[string] = line.strip().split(" ")
    if parts.len() == 0: continue
    if "*" in parts[0]: continue

    let
        rawValue: string = parts[0]
        codeValue: string = block:
            var r: string = rawValue.toCodeRepr()
            if r in needsQuotes: r = "`" & r & "`"
            r
        components: seq[string] = block:
            if parts.len() == 1: @[]
            else: parts[1 .. ^1]

    # Convert to string:
    let
        deprecationNotice: string = block:
            if "Deprecated" in components:
                " {.deprecated: \"This CSS value is deprecated.\".}"
            else: ""
        reference: string = "Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/" & rawValue
        notes: string = block:
            if components.len() == 0: ""
            else: "Notes: [" & components.join(", ") & "] "

    output.lines.add(&"    {codeValue}*{deprecationNotice}: CssProperty = \"{rawValue}\" ## CssValue `{rawValue}` {notes}{reference}")

output.lines.add("")
output.writeFile()
