import std/[strutils, strformat]
import parser

var output: OutputFile = newOutputFile("cssProperties.nim")
output.lines = @[
    "## CSS Values",
    "## ==========",
    "##",
    "## This module is autogenerated with a list of CSS values.",
    "",
    "type CssValue* = string",
    "",
    "const"
]
