import std/[strutils, strformat]
import parser

var output: OutputFile = newOutputFile("cssValuesFunctions.nim")
output.lines = @[
    "## CSS Value Functions",
    "## ===================",
    "##",
    "## This module is autogenerated with a list of CSS value functions.",
    ""
]
