import std/[strutils, strformat]
import parser

let needQuoting: seq[string] = @[
    "div",
    "object",
    "template",
    "var"
]

var output: OutputFile = newOutputFile("htmlElements.nim")
output.lines = @[
    "## HTML Elements",
    "## =============",
    "##",
    "## This module is autogenerated with a list of HTML elements.",
    "",
    "type HtmlTag* = string",
    "",
    "const"
]

for fileLine in parseFileLines("html-elements.txt"):
    let
        splitString: seq[string] = fileLine.split(" ")
        tag: string = splitString[0][1 .. ^2] # Remove brackets
        components: seq[string] = if splitString.len() == 1: @[] else: splitString[1 .. ^1]

        additionalInformation: string = block:
            if components.len() == 0: ""
            else: "Notes: [" & components.join(", ") & "] "

        deprecationNotice: string = block:
            if "Deprecated" notin components: ""
            else:
                " {.deprecated: \"Deprecated in newer HTML versions\".}"
        documentation: string = &"HtmlTag `{tag}` {additionalInformation}Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/{tag}"
        quote: string = if tag notin needQuoting: "" else: "`"

    let line: string = &"{quote}{tag}{quote}*{deprecationNotice}: HtmlTag = \"{tag}\" ## {documentation}"
    output.lines.add(line.indent(4))

output.lines.add("")
output.writeFile()
